image: maven:3.5.3-jdk-8

services:
  - postgres:11.2

variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"

  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd`are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

  # PostgreSQL docker's variable
  POSTGRES_DB: r2dbc-poc
  POSTGRES_USER: r2dbc-poc
  POSTGRES_PASSWORD: r2dbc-poc

  # application's variables
  DB_HOST: postgres
  LOG_DATEFORMAT_PATTERN: yyyy-MM-dd'T'HH:mm:ss'Z', Z

package:
  script: "mvn package $MAVEN_CLI_OPTS"
